import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Hearth & Grain Bakery",
    slug: "hearth-and-grain-bakery",
    bio: "Slow-fermented, wood-fired artisan bread baked every morning in our Lincoln stone-barn bakery. Long-fermentation sourdoughs, ancient grain loaves, and buttery pastries — all made by hand, no shortcuts.",
    story:
      "I gave up a career in structural engineering to become a baker. Most people thought I was mad. I'd spent weekends obsessively baking sourdough, reading about wild fermentation and heritage grains, and eventually I couldn't ignore it any more. In 2016 I converted an old stone barn on the edge of Lincoln into a bakery, installed a wood-fired deck oven, and started selling at the Saturday market. The response was overwhelming — within six months we had a waiting list. We use only stoneground flour from a mill in Norfolk, filtered water, and salt. Nothing else for our sourdoughs. Our enriched breads and pastries use free-range eggs and butter from a nearby dairy. We bake Monday to Saturday, starting at 4am. Every loaf is cooled, bagged, and dispatched the same morning.",
    location: "Bracebridge Heath, Lincoln",
    address: {
      line1: "The Old Stone Barn, Mill Lane",
      city: "Lincoln",
      county: "Lincolnshire",
      postcode: "LN4 2LP",
      country: "GB",
    },
    categories: ["bread", "pastries"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/sourdough.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@hearthandgrainbakery",
      facebook: "HearthAndGrain",
    },
    rating: 4.8,
    reviewCount: 524,
    createdAt: new Date("2016-09-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Classic White Sourdough",
    description:
      "Our flagship loaf — 72-hour cold-fermented white sourdough with a shatteringly crisp crust and a soft, open crumb. Made with stoneground white flour and our 8-year-old starter. Baked fresh every morning. Each loaf weighs approximately 800g.",
    slug: "classic-white-sourdough",
    category: "bread",
    price: 550,
    unit: "800g loaf",
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
      "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=800&q=80",
    ],
    dietary: ["vegan", "dairy-free"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Seeded Rye & Spelt Loaf",
    description:
      "A dense, nutty loaf combining dark rye flour and spelt with a generous coating of sunflower, pumpkin, and sesame seeds. Long fermentation gives it a complex, slightly sour flavour that deepens over 3–4 days. Excellent with smoked fish, cheese, or cold butter.",
    slug: "seeded-rye-spelt-loaf",
    category: "bread",
    price: 600,
    unit: "750g loaf",
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=800&q=80",
    ],
    dietary: ["vegan", "dairy-free"],
    allergens: ["gluten", "sesame"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Butter Croissants (4-pack)",
    description:
      "Classic laminated croissants made with 84-fat French butter, layered over three days for maximum flakiness. Glazed with egg wash and baked until deeply golden. Best eaten within two hours of baking — which is exactly when we dispatch them.",
    slug: "butter-croissants-4-pack",
    category: "pastries",
    price: 650,
    unit: "pack of 4",
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Cinnamon & Raisin Brioche",
    description:
      "A soft, pillowy brioche enriched with free-range eggs and Lincoln dairy butter, swirled with cinnamon sugar and plump sultanas. Baked in a pullman tin for a clean, sliceable loaf. Equally good toasted with butter or used for the world's best French toast.",
    slug: "cinnamon-raisin-brioche",
    category: "bread",
    price: 700,
    unit: "700g loaf",
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1606101273945-e9eba14a6d24?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Rosemary & Sea Salt Focaccia",
    description:
      "Our focaccia is made with a highly hydrated sourdough and dimpled generously before baking to pool extra-virgin olive oil. Topped with flaky Maldon salt and fresh rosemary, it comes out of the oven with a crisp base and a pillowy interior. Serves 4 as a side.",
    slug: "rosemary-sea-salt-focaccia",
    category: "bread",
    price: 500,
    unit: "serves 4",
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=800&q=80",
    ],
    dietary: ["vegan", "dairy-free"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Weekly Bread Subscription (4 loaves)",
    description:
      "Our most popular option — four loaves of your choice delivered every week. Choose from our full range when you subscribe, and swap varieties whenever you like. Free delivery included. Pause or cancel anytime with 48 hours' notice.",
    slug: "weekly-bread-subscription",
    category: "bread",
    price: 1800,
    unit: "4 loaves/week",
    stock: 999,
    images: [
      "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=800&q=80",
    ],
    dietary: ["vegan"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Pain au Chocolat (4-pack)",
    description:
      "Same laminated dough as our croissants, wrapped around two sticks of 70% Valrhona dark chocolate. Baked until the chocolate is molten and the pastry is deeply caramelised. A four-pack because one is never enough.",
    slug: "pain-au-chocolat-4-pack",
    category: "pastries",
    price: 750,
    unit: "pack of 4",
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy", "eggs"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Hearth & Grain Bakery",
    producerSlug: "hearth-and-grain-bakery",
    name: "Farmhouse White Bloomer",
    description:
      "A classic British white tin loaf made with a 24-hour sponge for flavour, baked in a clay-lined tin. Soft crumb, gentle crust. Perfect for sandwiches and toast. This is the bread your grandparents would have bought from the local bakery — before it all went wrong.",
    slug: "farmhouse-white-bloomer",
    category: "bread",
    price: 375,
    unit: "800g loaf",
    stock: 100,
    images: [
      "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=800&q=80",
    ],
    dietary: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "David C.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "I've been on the weekly subscription for three months and I genuinely cannot imagine going back to supermarket bread. The white sourdough is extraordinary — I've started turning down invitations just so I can stay home and eat toast.",
    createdAt: new Date("2024-04-05"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "Fiona M.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The croissants arrived still warm and they were genuinely better than anything I've had in Paris. Not exaggerating. The layering is perfect, the butter flavour is incredible. I order them every Friday now.",
    createdAt: new Date("2024-04-18"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Tom B.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The rye and spelt loaf changed my relationship with bread. I used to avoid dense loaves but this one is incredible — complex, nutty, satisfying. Keeps for days. Now I order two at a time.",
    createdAt: new Date("2024-05-02"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-1",
        productName: "Classic White Sourdough",
        producerId: "producer-1",
        producerName: "Hearth & Grain Bakery",
        price: 550,
        quantity: 2,
        unit: "800g loaf",
        imageUrl: "/images/hero.jpg",
      },
      {
        productId: "prod-3",
        productName: "Butter Croissants (4-pack)",
        producerId: "producer-1",
        producerName: "Hearth & Grain Bakery",
        price: 650,
        quantity: 1,
        unit: "pack of 4",
        imageUrl: "/images/hero.jpg",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "22 Steep Hill",
      city: "Lincoln",
      postcode: "LN2 1LT",
      country: "GB",
    },
    subtotal: 1750,
    commission: 0,
    deliveryFee: 295,
    total: 2045,
    stripePaymentIntentId: "pi_demo_bakery_001",
    createdAt: new Date("2024-04-08"),
    updatedAt: new Date("2024-04-09"),
  },
];
